# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=1000"]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.27.1
    hooks:
      - id: commitizen
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
        name: isort (python)
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
