version: "3"
services:
  cool-geo-app-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - "PORT=8080"
      - "DATABASE_URL=postgres://postgres:postgres@postgres:5432/cool-geo-app"
      - "DATABASE_SSL_MODE=disable"
      - "SECRET_KEY=1751072025a9f1a3a494416deb342e5e9054c5a63ea487c95b7cba3bf42efb81"
    depends_on:
      - postgres
    profiles:
      - cool-geo-app-api
  postgres:
    image: postgis/postgis:14-3.1
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cool-geo-app
    volumes:
      - ./db/data/:/tmp/data
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
